version: 2
updates:

  # Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"       # check tous les jours
    open-pull-requests-limit: 10
    commit-message:
      prefix: "maven"
    security-updates: true    # patch vulnérabilités critiques automatiquement

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    security-updates: true