name: Jacoco/PMD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  checks: write
  pull-requests: write  # pour poster le commentaire dans la PR

jobs:
  coverage-quality:
    name: Run Coverage & PMD Code Quality
    runs-on: ubuntu-latest
    # Create max_pmd_violations variable to control build failure threshold
    env:
      MAX_PMD_VIOLATIONS: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build and run tests
        run: mvn -B verify --file pom.xml

      - name: Generate JaCoCo badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.12.1
        with:
          generate-coverage-badge: true
          generate-branches-badge: true
          generate-summary: true

      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'category/java/errorprone.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false

      - name: Upload badges as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badges
          path: '*.svg'

      - name: Comment coverage & PMD summary on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          NEWLINE=$'\n'
          COVERAGE=$(awk "BEGIN {printf \"%.2f\", ${{ steps.jacoco.outputs.coverage }} * 100}")
          BRANCHES=$(awk "BEGIN {printf \"%.2f\", ${{ steps.jacoco.outputs.branches }} * 100}")
          PMD_TOTAL=$(cat pmd-report.sarif | jq '.runs[0].results | length')
          PMD_PERCENT=$(awk "BEGIN {printf \"%.2f\", $PMD_TOTAL * 100 / ${{ env.MAX_PMD_VIOLATIONS }}}")
          BODY="## Test Coverage & PMD Summary${NEWLINE}* __Coverage:__ ${COVERAGE}%${NEWLINE}* __Branch coverage:__ ${BRANCHES}%${NEWLINE}* __PMD violations:__ ${PMD_PERCENT}% (${PMD_TOTAL} violations)"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail build on PMD violations
        run: |
          echo "Detected PMD violations: ${{ steps.pmd.outputs.violations }}"
          if [ ${{ steps.pmd.outputs.violations }} -gt ${{ env.MAX_PMD_VIOLATIONS }} ]; then
            echo "⚠️ PMD violations exceed max allowed (${{ env.MAX_PMD_VIOLATIONS }})"
            exit 1
          fi