name: Release Build
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Build, Test & PMD
        run: mvn clean test pmd:pmd

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Generate Jacoco report
        run: mvn jacoco:report

      - name: Zip PMD
        run: zip -r pmd.zip target/reports/pmd

      - name: Zip JavaDoc
        run: zip -r apidocs.zip target/reports/apidocs

      - name: Zip Jacoco
        run: zip -r jacoco.zip target/site/jacoco

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          files: |
            pmd.zip
            apidocs.zip
            jacoco.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}